# Generated by Django 5.2.14 on 2026-06-08 13:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telegram', models.CharField(blank=True, help_text='Con o sin @; se normaliza al guardar.', max_length=80, verbose_name='Telegram (@usuario)')),
                ('whatsapp', models.CharField(blank=True, help_text='Número con código de país (ej. +51987654321).', max_length=40, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Mis créditos')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Ajustes de Jheliz Control',
                'verbose_name_plural': 'Ajustes de Jheliz Control',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='apps', help_text="Nombre del icono de Material Symbols (ej. 'movie', 'music_note').", max_length=60, verbose_name='Icono (Material Symbols)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jheliz_control/servicios/', verbose_name='Imagen')),
                ('icon', models.CharField(blank=True, help_text="Icono de respaldo si no hay imagen (ej. 'live_tv').", max_length=60, verbose_name='Icono (Material Symbols)')),
                ('color', models.CharField(default='#10b981', help_text='Color de acento de la tarjeta (hex).', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='gestion.servicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.CharField(max_length=160, verbose_name='Correo / usuario de la cuenta')),
                ('account_password', models.CharField(blank=True, max_length=160, verbose_name='Contraseña')),
                ('plan', models.CharField(choices=[('completa', 'Cuenta completa'), ('perfil', 'Perfil individual')], default='perfil', max_length=12, verbose_name='Plan')),
                ('profiles', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de perfiles (1 a 7). En cuenta completa, 1.', verbose_name='Perfiles')),
                ('profile_name', models.CharField(blank=True, max_length=80, verbose_name='Nombre de perfil')),
                ('profile_pin', models.CharField(blank=True, max_length=12, verbose_name='PIN')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo (venta al cliente)')),
                ('investment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Inversión (costo de adquisición)')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('expires_at', models.DateTimeField(verbose_name='Vence')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gestion.client', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gestion.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gestion.client', verbose_name='Cliente')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gestion.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos (ingresos / egresos)',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
