# Generated by Django 5.2.14 on 2026-06-08 14:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10, verbose_name='Precio mensual (S/)')),
                ('yape_holder', models.CharField(blank=True, max_length=120, verbose_name='Titular Yape')),
                ('yape_phone', models.CharField(blank=True, max_length=30, verbose_name='Número Yape')),
                ('yape_qr', models.ImageField(blank=True, help_text='QR de tu Yape para cobrar el alquiler.', upload_to='jheliz_control/yape/', verbose_name='QR de Yape')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones extra')),
            ],
            options={
                'verbose_name': 'Ajustes del SaaS (Jheliz Control)',
                'verbose_name_plural': 'Ajustes del SaaS (Jheliz Control)',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_clients', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_settings', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)'),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_services', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre del negocio')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('plan_expires_at', models.DateTimeField(blank=True, help_text='Hasta cuándo tiene acceso pagado. Vacío = nunca pagó.', null=True, verbose_name='Alquiler vence')),
                ('is_blocked', models.BooleanField(default=False, help_text='Si está activo, el inquilino no puede entrar aunque haya pagado.', verbose_name='Bloqueado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jc_tenant', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto')),
                ('days', models.PositiveIntegerField(default=30, verbose_name='Días que otorga')),
                ('proof', models.ImageField(blank=True, help_text='Captura del pago por Yape subida por el inquilino.', upload_to='jheliz_control/pagos/', verbose_name='Comprobante Yape')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gestion.tenant', verbose_name='Inquilino')),
            ],
            options={
                'verbose_name': 'Pago de alquiler',
                'verbose_name_plural': 'Pagos de alquiler (Yape)',
                'ordering': ['-created_at'],
            },
        ),
    ]
