# Generated by Django 5.2.14 on 2026-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_currency_to_soles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsettings',
            name='currency',
            field=models.CharField(default='S/', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='S/', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='S/', max_length=8, verbose_name='Moneda'),
        ),
    ]
