# Generated by Django 5.2.14 on 2026-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_controlsettings_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_label',
            field=models.CharField(blank=True, help_text='Nombre del plan (ej. Premium, Básico).', max_length=40, verbose_name='Plan de suscripción'),
        ),
    ]
