# Generated by Django 5.2.16 on 2026-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_subscription_plan_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saassettings',
            name='yape_holder',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='saassettings',
            name='yape_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Binance Pay ID / referencia'),
        ),
        migrations.AlterField(
            model_name='saassettings',
            name='yape_qr',
            field=models.ImageField(blank=True, help_text='QR de pago (Binance Pay) para cobrar el alquiler.', upload_to='jheliz_control/yape/', verbose_name='QR de pago'),
        ),
    ]
