# Generated by Django 5.2.16 on 2026-07-13 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_saassettings_yape_holder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=160, verbose_name='Correo / usuario')),
                ('password', models.CharField(blank=True, max_length=160, verbose_name='Contraseña')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendido')], default='available', max_length=12, verbose_name='Estado')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jc_stock_emails', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (inquilino)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_emails', to='gestion.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Correo en stock',
                'verbose_name_plural': 'Correos en stock',
                'ordering': ['status', 'service__name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'service', 'email'), name='uniq_stock_email_per_owner_service')],
            },
        ),
    ]
