# Generated by Django 5.2.16 on 2026-08-03 22:51

import config.private_storage
import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def _move_proofs(apps, source_root, destination_root):
    source_root = Path(source_root).resolve()
    destination_root = Path(destination_root).resolve()
    destination_root.mkdir(parents=True, exist_ok=True, mode=0o700)

    for model_name in ("RenewalRequest", "TenantPayment"):
        model = apps.get_model("gestion", model_name)
        for name in model.objects.exclude(proof="").values_list("proof", flat=True):
            source = (source_root / name).resolve()
            destination = (destination_root / name).resolve()
            if source_root not in source.parents or destination_root not in destination.parents:
                continue
            if not source.is_file():
                continue
            destination.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
            if not destination.exists():
                shutil.copy2(source, destination)
                destination.chmod(0o600)
            source.unlink()


def move_to_private_storage(apps, schema_editor):
    _move_proofs(apps, settings.MEDIA_ROOT, settings.PRIVATE_MEDIA_ROOT)


def move_back_to_public_storage(apps, schema_editor):
    _move_proofs(apps, settings.PRIVATE_MEDIA_ROOT, settings.MEDIA_ROOT)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_controlsettings_global_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalrequest',
            name='proof',
            field=models.ImageField(blank=True, null=True, storage=config.private_storage.PrivateMediaStorage(), upload_to='jheliz_control/renewal_proofs/'),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='proof',
            field=models.ImageField(blank=True, help_text='Captura del pago por Yape subida por el inquilino.', storage=config.private_storage.PrivateMediaStorage(), upload_to='jheliz_control/pagos/', verbose_name='Comprobante Yape'),
        ),
        migrations.RunPython(move_to_private_storage, move_back_to_public_storage),
    ]
