# Generated by Django 5.2.17 on 2026-09-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_separate_yape_binance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora declarada'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre del pagador'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='payer_phone_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='verification_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tenant_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='yape_security_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Código de seguridad Yape'),
        ),
    ]
