# Generated by Django 5.2.17 on 2026-08-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DigitalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="nombre")),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                ("color", models.CharField(default="#5b3df5", max_length=7, verbose_name="color")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "servicio digital",
                "verbose_name_plural": "servicios digitales",
                "ordering": ("name",),
            },
        ),
    ]
