# Generated by Django 5.2.17 on 2026-08-09 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Replacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("access", "Problema de acceso"),
                            ("blocked", "Cuenta bloqueada"),
                            ("service", "Falla del servicio"),
                            ("expired", "Cuenta vencida"),
                            ("other", "Otro"),
                        ],
                        max_length=16,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "replaced_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha de reposición",
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=500, verbose_name="notas internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_outgoing",
                        to="inventory.digitalaccount",
                        verbose_name="cuenta anterior",
                    ),
                ),
                (
                    "replacement_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_incoming",
                        to="inventory.digitalaccount",
                        verbose_name="cuenta de reposición",
                    ),
                ),
            ],
            options={
                "verbose_name": "reposición",
                "verbose_name_plural": "reposiciones",
                "ordering": ("-replaced_at", "-pk"),
            },
        ),
    ]
