services:
  web:
    environment:
      SECRET_KEY_FILE: /run/secrets/django_secret_key
      DATABASE_URL_FILE: /run/secrets/database_url
      FIELD_ENCRYPTION_KEY_FILE: /run/secrets/field_encryption_key
    secrets:
      - django_secret_key
      - database_url
      - field_encryption_key

  db:
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  telegram_bot:
    environment:
      SECRET_KEY_FILE: /run/secrets/django_secret_key
      DATABASE_URL_FILE: /run/secrets/database_url
      FIELD_ENCRYPTION_KEY_FILE: /run/secrets/field_encryption_key
    secrets:
      - django_secret_key
      - database_url
      - field_encryption_key

  codes_bot:
    environment:
      SECRET_KEY_FILE: /run/secrets/django_secret_key
      DATABASE_URL_FILE: /run/secrets/database_url
      FIELD_ENCRYPTION_KEY_FILE: /run/secrets/field_encryption_key
      TELEGRAM_CODES_BOT_TOKEN_FILE: /run/secrets/telegram_codes_bot_token
      CODES_IMAP_PASSWORD_FILE: /run/secrets/codes_imap_password
      CODES_IMAP2_PASSWORD_FILE: /run/secrets/codes_imap2_password
    secrets:
      - django_secret_key
      - database_url
      - field_encryption_key
      - telegram_codes_bot_token
      - codes_imap_password
      - codes_imap2_password

  disney_bot:
    environment:
      SECRET_KEY_FILE: /run/secrets/django_secret_key
      DATABASE_URL_FILE: /run/secrets/database_url
      FIELD_ENCRYPTION_KEY_FILE: /run/secrets/field_encryption_key
      CODES_IMAP_PASSWORD_FILE: /run/secrets/codes_imap_password
      CODES_IMAP2_PASSWORD_FILE: /run/secrets/codes_imap2_password
    secrets:
      - django_secret_key
      - database_url
      - field_encryption_key
      - codes_imap_password
      - codes_imap2_password

  backup:
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

secrets:
  django_secret_key:
    file: ./secrets/django_secret_key.txt
  database_url:
    file: ./secrets/database_url.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  field_encryption_key:
    file: ./secrets/field_encryption_key.txt
  telegram_codes_bot_token:
    file: ./secrets/telegram_codes_bot_token.txt
  codes_imap_password:
    file: ./secrets/codes_imap_password.txt
  codes_imap2_password:
    file: ./secrets/codes_imap2_password.txt
