# Generated by Django 5.2.13 on 2026-05-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0017_paymentsettings_usd_rate_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordOrderThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('thread_id', models.CharField(db_index=True, max_length=32)),
                ('root_message_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_status_posted', models.CharField(blank=True, max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_thread', to='orders.order')),
            ],
            options={
                'verbose_name': 'Thread Discord de pedido',
                'verbose_name_plural': 'Threads Discord de pedidos',
            },
        ),
    ]
