# Generated by Django 5.2.13 on 2026-05-08 23:07

import django.db.models.deletion
import livechat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=livechat.models._generate_room_token, editable=False, help_text='Identificador opaco que vive en el navegador del visitante.', max_length=48, unique=True, verbose_name='Token público')),
                ('customer_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Nombre')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=10, verbose_name='Estado')),
                ('page_url', models.CharField(blank=True, default='', help_text='URL desde la que se abrió el chat por primera vez.', max_length=500, verbose_name='Página al iniciar')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_admin_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (si está logueado)')),
            ],
            options={
                'verbose_name': 'Sala de chat',
                'verbose_name_plural': 'Salas de chat',
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Cliente'), ('admin', 'Admin'), ('system', 'Sistema')], max_length=10)),
                ('body', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, help_text='Usuario admin que mandó el mensaje, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='livechat.chatroom')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status', '-last_message_at'], name='livechat_ch_status_41f067_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['customer_email'], name='livechat_ch_custome_cb5584_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='livechat_ch_room_id_a66fd3_idx'),
        ),
    ]
