# Generated by Django 5.2.14 on 2026-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen adjunta enviada desde el chat.', max_length=500, null=True, upload_to='livechat/images/%Y/%m/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje'),
        ),
    ]
