# Generated by Django 5.2.13 on 2026-04-27 11:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Visible sólo para ti. Ej: 'renueva siempre el 5', 'pide recordatorio', 'cliente VIP'.", verbose_name='Notas internas (admin)'),
        ),
    ]
