# Generated by Django 5.2.13 on 2026-04-27 22:42

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_user_admin_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
