# Generated by Django 5.2.13 on 2026-05-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='Endpoint del push service')),
                ('p256dh', models.CharField(max_length=128, verbose_name='Clave p256dh (Base64URL)')),
                ('auth', models.CharField(max_length=64, verbose_name='Clave auth (Base64URL)')),
                ('user_agent', models.CharField(blank=True, help_text='Para distinguir Chrome desktop / Safari iOS / etc.', max_length=300, verbose_name='User-Agent del navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, help_text='Si la última notificación falló, se guarda el error acá.', max_length=200, verbose_name='Último error de envío')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Cuando llega a 3, se desactiva la subscripción.', verbose_name='Veces fallidas seguidas')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado (puede ser null si el cliente nunca se logueó).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscripción push',
                'verbose_name_plural': 'Subscripciones push',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_enabled', 'created_at'], name='accounts_pu_is_enab_44ec55_idx')],
            },
        ),
    ]
