# Generated by Django 5.2.13 on 2026-05-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a recargar (S/).', max_digits=10, verbose_name='Monto')),
                ('method', models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin'), ('transfer', 'Transferencia / depósito'), ('mp', 'Mercado Pago'), ('other', 'Otro')], default='yape', max_length=20, verbose_name='Método')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_proof', models.ImageField(blank=True, help_text='Captura del comprobante de pago.', upload_to='wallet/recharges/', verbose_name='Comprobante')),
                ('user_note', models.TextField(blank=True, help_text='Comentario opcional para el admin.', verbose_name='Nota del distribuidor')),
                ('admin_note', models.TextField(blank=True, help_text='Notas privadas del admin.', verbose_name='Nota interna')),
                ('rejection_reason', models.TextField(blank=True, help_text='Mensaje que ve el distribuidor cuando se rechaza.', verbose_name='Motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_recharges_decided', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Movimiento creado cuando se aprobó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_origin', to='accounts.wallettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de recarga',
                'verbose_name_plural': 'Solicitudes de recarga',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='wrecharge_status_idx'), models.Index(fields=['user', '-created_at'], name='wrecharge_user_idx')],
            },
        ),
    ]
