# Generated by Django 5.2.14 on 2026-06-28 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_walletrecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo'),
        ),
    ]
