# Generated by Django 5.2.16 on 2026-07-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrecharge',
            name='method',
            field=models.CharField(choices=[('binance', 'Binance Pay'), ('transfer', 'Transferencia / depósito'), ('mp', 'Mercado Pago'), ('other', 'Otro')], default='transfer', max_length=20, verbose_name='Método'),
        ),
    ]
