# Generated by Django 5.2.13 on 2026-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identificador interno, ej: 'Cómo activar Office 2021'.", max_length=120, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('netflix', 'Netflix'), ('disney', 'Disney+'), ('spotify', 'Spotify'), ('office', 'Office / Microsoft'), ('windows', 'Windows'), ('adobe', 'Adobe'), ('general', 'General'), ('refund', 'Reembolso / garantía'), ('account', 'Activación / acceso')], db_index=True, default='general', max_length=20, verbose_name='Categoría')),
                ('subject', models.CharField(blank=True, help_text='Si la plantilla se usa al iniciar un ticket o email.', max_length=160, verbose_name='Asunto sugerido')),
                ('body', models.TextField(help_text='Texto que se inserta. Puedes usar {nombre}, {pedido}, {producto}, {telefono}, {fecha} como variables.', verbose_name='Cuerpo del mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('use_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Veces usada')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última vez usada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de respuesta',
                'verbose_name_plural': 'Plantillas de respuesta',
                'ordering': ('category', 'name'),
            },
        ),
    ]
