# Generated by Django 5.2.13 on 2026-05-03 13:09

import django.db.models.deletion
import support.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_reminderrunlog'),
        ('support', '0002_replytemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'Cliente final'), ('distributor', 'Distribuidor')], db_index=True, default='customer', max_length=20)),
                ('platform', models.CharField(choices=[('netflix', 'Netflix'), ('disney', 'Disney+'), ('prime', 'Amazon Prime Video'), ('max', 'Max / HBO'), ('spotify', 'Spotify'), ('crunchyroll', 'Crunchyroll'), ('apple', 'Apple TV+'), ('vix', 'ViX'), ('paramount', 'Paramount+'), ('youtube', 'YouTube Premium'), ('other', 'Otra')], max_length=20)),
                ('account_email', models.EmailField(help_text='Email con el que el cliente inicia sesión en la plataforma.', max_length=254, verbose_name='Email de la cuenta')),
                ('contact_email', models.EmailField(blank=True, help_text='Opcional. Para que te avisemos si el código cambia.', max_length=254, verbose_name='Tu email de contacto')),
                ('order_number', models.CharField(blank=True, max_length=40, verbose_name='N° de pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20)),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Código')),
                ('code_type', models.CharField(blank=True, choices=[('login', 'Inicio de sesión'), ('device', 'Activación de dispositivo / TV'), ('home', 'Hogar / Estoy de viaje'), ('reset_link', 'Link de restablecer contraseña'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de código')),
                ('admin_note', models.CharField(blank=True, help_text='Texto opcional que verá el cliente junto al código.', max_length=200, verbose_name='Nota para el cliente')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo de rechazo')),
                ('token', models.CharField(db_index=True, default=support.models._gen_token, editable=False, help_text='Identificador público para consultar el estado desde la web.', max_length=32, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Pedido asociado si se pudo resolver por order_number.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_requests', to='orders.order')),
                ('responded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Si el cliente/distribuidor estaba logueado al solicitar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de código',
                'verbose_name_plural': 'Solicitudes de código',
                'ordering': ('-created_at',),
            },
        ),
    ]
