# Generated by Django 5.2.13 on 2026-05-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_coderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderequest',
            name='note',
            field=models.CharField(blank=True, help_text='Detalle opcional que el cliente escribe al pedir el código.', max_length=300, verbose_name='Mensaje del cliente'),
        ),
        migrations.AddField(
            model_name='coderequest',
            name='requested_code_type',
            field=models.CharField(blank=True, choices=[('login', '🔑 Código de inicio de sesión'), ('device', '📺 Código de activación de TV / dispositivo'), ('home', '🏠 Código de hogar / Estoy de viaje'), ('reset_link', '🔐 Link para restablecer contraseña'), ('other', '❓ Otro (explico abajo)')], help_text='Lo que el cliente seleccionó al pedir el código.', max_length=20, verbose_name='Tipo de código solicitado'),
        ),
    ]
