'use client';

import {useEffect,useMemo,useState} from 'react';

type Product={id:string;sku:string;name:string;category:string;description:string;priceCents:number;currency:string;imageUrl?:string|null;_count:{inventory:number}};

const serviceStyle:Record<string,{short:string,color:string}>={
  NETFLIX:{short:'N',color:'#e50914'},PRIME:{short:'prime',color:'#1399ff'},MAX:{short:'max',color:'#6f4cff'},
  DISNEY:{short:'D+',color:'#087bea'},SPOTIFY:{short:'●',color:'#1ed760'},YOUTUBE:{short:'▶',color:'#ff0033'},
  CRUNCHYROLL:{short:'C',color:'#f47521'},CANVA:{short:'C',color:'#7d2ae8'},IPTV:{short:'TV',color:'#22c7bd'}
};
const money=(c:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(c/100);

export default function Store(){
  const[products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[cart,setCart]=useState<Product[]>([]),[loading,setLoading]=useState(true),[menu,setMenu]=useState(false);
  useEffect(()=>{fetch('/api/store/products').then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>setProducts([])).finally(()=>setLoading(false))},[]);
  const categories=useMemo(()=>['Todos',...Array.from(new Set(products.map(p=>p.category||'Streaming')))], [products]);
  const shown=products.filter(p=>(category==='Todos'||p.category===category)&&`${p.name} ${p.sku} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
  const add=(p:Product)=>setCart(c=>[...c,p]);
  return <div className="store-shell">
    <header className="store-header"><a className="store-brand" href="#inicio"><span>J</span><b>Jheliz</b><small>Digital</small></a><nav className={menu?'show':''}><a href="#inicio">Inicio</a><a href="#categorias">Categorías</a><a href="#productos">Productos</a><a href="#como-comprar">Cómo comprar</a></nav><div className="store-actions"><a className="admin-link" href="/admin">Administrar</a><button className="cart-button" onClick={()=>document.getElementById('carrito')?.scrollIntoView({behavior:'smooth'})}>Carrito <b>{cart.length}</b></button><button className="menu-button" onClick={()=>setMenu(!menu)}>☰</button></div></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-copy"><span className="store-kicker">ENTREGA DIGITAL SEGURA</span><h1>Todo tu entretenimiento,<br/><em>en un solo lugar.</em></h1><p>Compra cuentas completas de streaming. Recibe correo y contraseña de manera rápida, privada y ordenada.</p><div className="hero-buttons"><a href="#productos" className="shop-primary">Ver productos</a><a href="#como-comprar" className="shop-secondary">Cómo funciona</a></div><div className="trust-row"><span>✓ Compra protegida</span><span>✓ Stock en tiempo real</span><span>✓ Soporte directo</span></div></div><div className="hero-visual"><div className="orb one"></div><div className="orb two"></div><div className="stream-card card-a"><Logo sku="NETFLIX"/><span>Netflix</span><b>Cuenta completa</b></div><div className="stream-card card-b"><Logo sku="PRIME"/><span>Prime Video</span><b>Acceso privado</b></div><div className="stream-card card-c"><Logo sku="MAX"/><span>Max</span><b>30 días</b></div></div></section>
      <section className="benefits"><article><i>⚡</i><div><b>Entrega rápida</b><span>Credenciales después del pago</span></div></article><article><i>▣</i><div><b>Cuentas completas</b><span>Correo y contraseña</span></div></article><article><i>♧</i><div><b>Soporte humano</b><span>Te ayudamos con tu compra</span></div></article></section>
      <section className="catalog" id="productos"><div className="section-title"><div><span className="store-kicker">CATÁLOGO</span><h2>Servicios disponibles</h2><p>Elige tu plataforma favorita y compra sin salir de la web.</p></div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar Netflix, Prime, Max..."/></label></div><div className="category-tabs" id="categorias">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>{loading?<div className="store-loading"><i></i><span>Cargando catálogo…</span></div>:shown.length?<div className="product-grid">{shown.map((p,i)=><ProductCard key={p.id} product={p} index={i} add={add}/>)}</div>:<div className="no-products"><b>No encontramos productos</b><span>Prueba otra búsqueda o agrega stock desde el panel.</span></div>}</section>
      <section className="how" id="como-comprar"><span className="store-kicker">SIMPLE Y CLARO</span><h2>Compra en tres pasos</h2><div><article><b>01</b><h3>Elige tu cuenta</h3><p>Revisa precio, duración y stock disponible.</p></article><article><b>02</b><h3>Realiza el pago</h3><p>Completa tus datos y paga desde la web.</p></article><article><b>03</b><h3>Recibe tus datos</h3><p>Obtén el correo y contraseña de tu cuenta completa.</p></article></div></section>
      <section className="cart-section" id="carrito"><div><span className="store-kicker">TU PEDIDO</span><h2>{cart.length?`${cart.length} producto${cart.length>1?'s':''} en el carrito`:'Tu carrito está vacío'}</h2><p>{cart.length?'Revisa tus productos antes de continuar.':'Explora el catálogo y agrega una cuenta completa.'}</p></div>{cart.length?<div className="cart-box"><div>{cart.map((p,i)=><p key={`${p.id}-${i}`}><span><Logo sku={p.sku}/>{p.name}</span><b>{money(p.priceCents)}</b><button onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}>×</button></p>)}</div><footer><span>Total <b>{money(cart.reduce((n,p)=>n+p.priceCents,0))}</b></span><button onClick={()=>alert('El pago web seguro se habilitará en el siguiente paso de configuración.')}>Continuar al pago</button></footer></div>:<a className="shop-primary" href="#productos">Explorar catálogo</a>}</section>
    </main><footer className="store-footer"><a className="store-brand" href="#inicio"><span>J</span><b>Jheliz</b><small>Digital</small></a><p>Productos digitales · Cuentas completas · Soporte postventa</p><small>© 2026 Jheliz. Todos los derechos reservados.</small></footer>
  </div>
}

function Logo({sku}:{sku:string}){const key=sku.toUpperCase().replace(/[^A-Z]/g,'');const style=serviceStyle[key]||{short:sku.slice(0,2).toUpperCase(),color:'#6f7bf7'};return <i className="service-logo" style={{'--logo-color':style.color} as React.CSSProperties}>{style.short}</i>}
function ProductCard({product,index,add}:{product:Product;index:number;add:(p:Product)=>void}){const stock=product._count.inventory;return <article className="product-card" style={{animationDelay:`${Math.min(index,8)*55}ms`}}><div className="product-cover"><Logo sku={product.sku}/><span className={stock?'stock':'stock out'}>{stock?`${stock} disponibles`:'Agotado'}</span></div><div className="product-info"><small>{product.category||'Streaming'}</small><h3>{product.name}</h3><p>{product.description||'Cuenta completa con correo y contraseña.'}</p><div className="product-tags"><span>Cuenta completa</span><span>Entrega digital</span></div><footer><div><small>Precio</small><strong>{money(product.priceCents)}</strong></div><button disabled={!stock} onClick={()=>add(product)}>{stock?'Comprar':'Sin stock'}</button></footer></div></article>}
