# Generated by Django 5.2.13 on 2026-04-27 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_customerplan_distributorplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Descripción')),
                ('emoji', models.CharField(blank=True, default='📝', max_length=4, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Categoría de blog',
                'verbose_name_plural': 'Categorías de blog',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(help_text='Resumen corto que aparece en el listado y en la meta description.', max_length=300, verbose_name='Extracto')),
                ('body', models.TextField(help_text='Acepta Markdown: # Título, ## Subtítulo, **negrita**, *cursiva*, listas con - o 1.', verbose_name='Contenido (Markdown)')),
                ('cover_image', models.ImageField(blank=True, help_text='Recomendado 1200x630 px (Open Graph). Aparece en la cabecera del post y en redes sociales.', upload_to='blog/covers/', verbose_name='Imagen de portada')),
                ('cover_alt', models.CharField(blank=True, max_length=160, verbose_name='Texto alternativo')),
                ('seo_title', models.CharField(blank=True, help_text='Si está vacío, usa el título normal. Máx 60-70 caracteres para Google.', max_length=70, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, help_text='Si está vacío, usa el extracto. Máx 155-160 caracteres.', max_length=160, verbose_name='Meta description')),
                ('seo_keywords', models.CharField(blank=True, max_length=300, verbose_name='Keywords (separadas por coma)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Si está marcado, aparece arriba del listado de blog.', verbose_name='Destacado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visitas')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Se mostrarán como CTA al final del artículo.', related_name='blog_posts', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Post de blog',
                'verbose_name_plural': 'Posts de blog',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_status_pub_idx'), models.Index(fields=['slug'], name='blog_slug_idx')],
            },
        ),
    ]
