# Generated by Django 5.2.13 on 2026-04-27 05:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('emoji', models.CharField(blank=True, default='🎉', max_length=8, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('audience', models.CharField(choices=[('cliente', 'Cliente final (perfiles)'), ('distribuidor', 'Distribuidor (cuentas completas)'), ('ambos', 'Ambos')], default='ambos', max_length=20, verbose_name='Público')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('mode', models.CharField(choices=[('perfil', 'Cuenta compartida (por perfil)'), ('completa', 'Cuenta completa'), ('licencia', 'Licencia / código')], default='perfil', max_length=20, verbose_name='Modo de venta')),
                ('short_description', models.CharField(blank=True, max_length=180, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='Emoji/icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en tienda')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado en home')),
                ('delivery_is_instant', models.BooleanField(default=True, verbose_name='Entrega inmediata')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3, verbose_name='Rating mostrado')),
                ('sold_badge', models.CharField(blank=True, help_text='Ej: +500, +10K', max_length=20, verbose_name='Etiqueta de ventas')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: 1 mes, 3 meses, Licencia de por vida', max_length=80, verbose_name='Nombre')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='0 = sin expiración (licencias perpetuas).', verbose_name='Duración en días')),
                ('price_customer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio cliente (S/)')),
                ('price_distributor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio distribuidor (S/)')),
                ('available_for_customer', models.BooleanField(default=True, verbose_name='Visible cliente final')),
                ('available_for_distributor', models.BooleanField(default=True, verbose_name='Visible distribuidor')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('order', 'duration_days'),
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.TextField(help_text='Texto libre que recibirá el cliente. Ej:\nCorreo: foo@bar.com\nContraseña: 1234\nPerfil: Perfil 2\nPIN: 0000', verbose_name='Credenciales')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='Etiqueta interna')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('disabled', 'Deshabilitada')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Si queda en blanco, el stock sirve para cualquier plan del producto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'status'], name='catalog_sto_product_d9fb48_idx'), models.Index(fields=['plan', 'status'], name='catalog_sto_plan_id_a5d57e_idx')],
            },
        ),
    ]
