# Generated by Django 5.2.13 on 2026-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_customer_profile_data',
            field=models.BooleanField(default=True, help_text='Aplica a productos por perfil (Netflix, Disney, etc). Desactiva para licencias donde el cliente no elige nada.', verbose_name='Pedir al cliente nombre de perfil y PIN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_is_instant',
            field=models.BooleanField(default=False, help_text='Si está activo, se asigna un stock automáticamente. Por defecto, la entrega es manual y el admin crea el perfil con los datos que pidió el cliente.', verbose_name='Entrega inmediata'),
        ),
    ]
