# Generated by Django 5.2.13 on 2026-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_requires_customer_profile_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='low_stock_alert_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Cuando el stock disponible cae por debajo de este número, se envía una alerta por Telegram al admin.', verbose_name='Umbral de stock bajo'),
        ),
    ]
