# Generated by Django 5.2.13 on 2026-04-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_plan_low_stock_alert_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Autor')),
                ('city', models.CharField(default='Lima', max_length=80, verbose_name='Ciudad')),
                ('text', models.TextField(verbose_name='Reseña')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Estrellas')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
