# Generated by Django 5.2.13 on 2026-04-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Plan — Cliente final',
                'verbose_name_plural': 'Planes — Cliente final',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.plan',),
        ),
        migrations.CreateModel(
            name='DistributorPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Plan — Distribuidor',
                'verbose_name_plural': 'Planes — Distribuidor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.plan',),
        ),
    ]
