# Generated by Django 5.2.13 on 2026-04-28 02:23

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_customerplan_distributorplan'),
        ('orders', '0008_coupon_order_coupon_code_order_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Solo para identificarlo en el admin, ej: 'Black Friday 2026'.", max_length=80, verbose_name='Nombre interno')),
                ('text', models.CharField(help_text='Texto principal del banner. Soporta emojis.', max_length=180, verbose_name='Texto')),
                ('coupon_code', models.CharField(blank=True, help_text="Si se llena, se muestra un botón 'Copiar código'.", max_length=40, verbose_name='Código de cupón')),
                ('cta_label', models.CharField(blank=True, default='Ver ofertas', max_length=40, verbose_name='Texto del botón')),
                ('cta_url', models.CharField(blank=True, help_text='Ruta relativa (ej. /productos/) o URL completa.', max_length=200, verbose_name='URL del botón')),
                ('countdown_to', models.DateTimeField(blank=True, help_text="Si se llena, se muestra un contador. Suele coincidir con 'Termina'.", null=True, verbose_name='Cuenta regresiva hasta')),
                ('style', models.CharField(choices=[('pink', 'Rosa Jheliz (recomendado)'), ('dark', 'Negro'), ('amber', 'Ámbar / oferta'), ('emerald', 'Verde / nuevo'), ('slate', 'Gris claro')], default='pink', max_length=10, verbose_name='Estilo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vacío = empieza inmediatamente.', null=True, verbose_name='Empieza')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vacío = sin fecha de fin (siempre visible mientras esté activo).', null=True, verbose_name='Termina')),
                ('show_only_on_home', models.BooleanField(default=False, help_text='Si lo desactivas, se muestra en todas las páginas.', verbose_name='Solo en la página de inicio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner promocional',
                'verbose_name_plural': 'Banners promocionales',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='Ciudad')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=5, verbose_name='Estrellas')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('photo', models.ImageField(blank=True, help_text='Captura o foto opcional (máx. ~2MB).', null=True, upload_to='reviews/', verbose_name='Foto')),
                ('is_verified', models.BooleanField(default=False, help_text='True si la reseña está ligada a un pedido entregado.', verbose_name='Compra verificada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente moderación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=12, verbose_name='Estado')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('token', models.CharField(default=catalog.models._generate_review_token, editable=False, help_text='Token único para el link mágico de envío.', max_length=48, unique=True, verbose_name='Token')),
                ('token_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Pedido que originó la reseña (verificación).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña verificada',
                'verbose_name_plural': 'Reseñas verificadas',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'status'], name='review_prod_status_idx'), models.Index(fields=['status', '-created_at'], name='review_status_created_idx')],
            },
        ),
    ]
