# Generated by Django 5.2.13 on 2026-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_promobanner_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jheliz', help_text='Aparece en el header, footer y emails.', max_length=80, verbose_name='Nombre del sitio')),
                ('tagline', models.CharField(blank=True, default='Cuentas oficiales y licencias premium en Perú', max_length=160, verbose_name='Tagline corto')),
                ('logo', models.ImageField(blank=True, help_text='Reemplaza el logo del header. PNG transparente recomendado (200×60).', null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Icono de la pestaña del navegador. ICO o PNG 64×64.', null=True, upload_to='site/', verbose_name='Favicon')),
                ('hero_title', models.CharField(blank=True, default='Streaming y licencias premium', max_length=120, verbose_name='Título del hero')),
                ('hero_subtitle', models.CharField(blank=True, default='Netflix, Disney+, Spotify, Office y más — cuentas oficiales con garantía.', max_length=200, verbose_name='Subtítulo del hero')),
                ('hero_cta_text', models.CharField(default='Ver catálogo', max_length=40, verbose_name='Texto del botón CTA')),
                ('whatsapp_number', models.CharField(blank=True, default='51999999999', help_text='Ej: 51999999999 (sin + ni espacios). Se usa en el botón flotante.', max_length=20, verbose_name='WhatsApp (con código país, sin +)')),
                ('whatsapp_message', models.CharField(default='Hola Jheliz, tengo una consulta sobre sus productos.', max_length=200, verbose_name='Mensaje pre-rellenado de WhatsApp')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('legal_business_name', models.CharField(blank=True, help_text="Nombre legal de la empresa, ej: 'Jheliz Services E.I.R.L.'", max_length=160, verbose_name='Razón social')),
                ('legal_ruc', models.CharField(blank=True, help_text='11 dígitos del RUC de la empresa.', max_length=20, verbose_name='RUC')),
                ('legal_address', models.CharField(blank=True, max_length=200, verbose_name='Dirección física')),
                ('seo_default_image', models.ImageField(blank=True, help_text='Imagen que aparece al compartir el sitio en WhatsApp/Facebook (1200×630).', null=True, upload_to='site/', verbose_name='Imagen OG por defecto')),
                ('seo_meta_description', models.CharField(blank=True, default='Cuentas premium oficiales: Netflix, Disney+, Spotify, Office y más. Pago Yape o Mercado Pago. Garantía 30 días.', max_length=200, verbose_name='Meta descripción (SEO)')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Si está activo, se muestra una página de mantenimiento en lugar del sitio normal.', verbose_name='Modo mantenimiento')),
                ('maintenance_message', models.TextField(blank=True, default='Volvemos en unos minutos. ¡Disculpa las molestias!', verbose_name='Mensaje de mantenimiento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
