# Generated by Django 5.2.13 on 2026-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('defective', 'Caída / Reportada'), ('disabled', 'Deshabilitada')], default='available', max_length=20),
        ),
    ]
