# Generated by Django 5.2.13 on 2026-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whatsapp_sales_copy',
            field=models.TextField(blank=True, help_text='Texto pre-armado que el distribuidor copia al instante para reenviar a sus clientes finales. Si está vacío se genera uno automático con nombre del producto y precios. Podés usar emojis y saltos de línea.', verbose_name='Plantilla para WhatsApp (distribuidores)'),
        ),
    ]
