# Generated by Django 5.2.13 on 2026-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_stockitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de reclamación')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre completo')),
                ('documento_tipo', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=10, verbose_name='Tipo de documento')),
                ('documento_numero', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('domicilio', models.CharField(blank=True, max_length=200, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('es_menor', models.BooleanField(default=False, verbose_name='Soy menor de edad')),
                ('padre_nombre', models.CharField(blank=True, max_length=160, verbose_name='Nombre del padre / madre / representante')),
                ('padre_documento', models.CharField(blank=True, max_length=20, verbose_name='Documento del representante')),
                ('tipo_bien', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10, verbose_name='Tipo de bien')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto reclamado (S/)')),
                ('descripcion_bien', models.CharField(max_length=300, verbose_name='Descripción del producto / servicio')),
                ('pedido_referencia', models.CharField(blank=True, max_length=50, verbose_name='N° de pedido (si aplica)')),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo (disconformidad con producto/servicio)'), ('queja', 'Queja (disconformidad con la atención)')], max_length=10, verbose_name='Tipo')),
                ('detalle', models.TextField(verbose_name='Detalle del reclamo / queja')),
                ('pedido_consumidor', models.TextField(help_text='¿Qué solicita el consumidor para resolver el caso?', verbose_name='Pedido del consumidor')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='recibido', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta del proveedor')),
                ('respondido_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de presentación')),
            ],
            options={
                'verbose_name': 'Reclamación (Libro Indecopi)',
                'verbose_name_plural': 'Libro de Reclamaciones (Indecopi)',
                'ordering': ('-created_at',),
            },
        ),
    ]
