# Generated by Django 5.2.13 on 2026-05-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_whatsapp_sales_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='provider_expires_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo vence la cuenta original (no la del cliente).', null=True, verbose_name='Vencimiento en proveedor'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='provider_expiry_1d_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='provider_expiry_3d_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['provider_expires_at'], name='stock_provexp_idx'),
        ),
    ]
