# Generated by Django 5.2.13 on 2026-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, help_text='Ej: G-XXXXXXXXXX (de Google Analytics 4 → Admin → Streams).', max_length=20, verbose_name='GA4 Measurement ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_ads_id',
            field=models.CharField(blank=True, help_text='Ej: AW-123456789 (opcional, para Google Ads).', max_length=30, verbose_name='Google Ads Conversion ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Ej: 1234567890123456 (de Meta Business → Eventos → Pixels).', max_length=20, verbose_name='Meta Pixel ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, help_text='Opcional, para retargeting en TikTok.', max_length=30, verbose_name='TikTok Pixel ID'),
        ),
    ]
