# Generated by Django 5.2.13 on 2026-05-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_merge_legal_tracking_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_customer_channel_url',
            field=models.URLField(blank=True, default='https://t.me/jheliztvavisos', help_text='Canal público de avisos para clientes finales (ofertas, novedades).', verbose_name='Canal Telegram – clientes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_distributor_channel_url',
            field=models.URLField(blank=True, default='https://t.me/jhelizservicetv', help_text='Canal público con info y avisos para distribuidores.', verbose_name='Canal Telegram – distribuidores'),
        ),
    ]
