# Generated by Django 5.2.13 on 2026-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_sitesettings_telegram_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telegram_audience',
            field=models.CharField(choices=[('both', 'Ambos canales (clientes + distribuidores)'), ('customer', 'Solo canal de clientes'), ('distributor', 'Solo canal de distribuidores'), ('none', 'No publicar en ningún canal')], default='both', help_text="Elige a qué canal(es) se publica este producto cuando se activa o se usa la acción 'Publicar al canal' del admin.", max_length=20, verbose_name='Publicar en Telegram'),
        ),
    ]
