# Generated by Django 5.2.13 on 2026-05-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_telegram_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Se usa en la URL: jhelizservicestv.xyz/plataforma/<slug>/', max_length=80, unique=True, verbose_name='Slug (URL)')),
                ('name', models.CharField(help_text='Ej: Netflix, Disney+, Spotify, HBO Max.', max_length=80, verbose_name='Nombre de plataforma')),
                ('tagline', models.CharField(blank=True, help_text='Frase corta debajo del H1. Ej: "Cuentas premium desde S/5/mes".', max_length=180, verbose_name='Tagline (subtítulo)')),
                ('hero_description', models.TextField(blank=True, help_text='Texto introductorio debajo del tagline (1-2 párrafos). HTML permitido.', verbose_name='Descripción del hero')),
                ('body_html', models.TextField(blank=True, help_text='HTML extra para la sección intermedia (beneficios, cómo funciona, etc.).', verbose_name='Contenido adicional (HTML)')),
                ('seo_title', models.CharField(blank=True, help_text='Aparece en los resultados de Google. Máx 60 caracteres ideal.', max_length=70, verbose_name='Meta title (SEO)')),
                ('seo_description', models.CharField(blank=True, help_text='Descripción que muestra Google. Máx 160 caracteres ideal.', max_length=200, verbose_name='Meta description (SEO)')),
                ('og_image', models.ImageField(blank=True, help_text='Imagen que se muestra al compartir en redes (1200x630 recomendado).', null=True, upload_to='landings/', verbose_name='Imagen Open Graph')),
                ('accent_color', models.CharField(blank=True, default='#ec4899', help_text='Color HEX del hero, ej: #e50914 (Netflix rojo), #0063e5 (Disney+ azul).', max_length=7, verbose_name='Color de acento (hex)')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marca para mostrar en el hero.', null=True, upload_to='landings/', verbose_name='Logo de plataforma')),
                ('faq', models.JSONField(blank=True, default=list, help_text='Lista JSON: [{"q": "¿Pregunta?", "a": "Respuesta"}, ...]', verbose_name='FAQ (preguntas frecuentes)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Si se setea, se muestran los productos activos de esta categoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landings', to='catalog.category')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='Productos destacados manualmente (opcional, si se setean tienen preferencia sobre la categoría).', related_name='landings', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Landing SEO (plataforma)',
                'verbose_name_plural': 'Landings SEO (plataformas)',
                'ordering': ('order', 'name'),
            },
        ),
    ]
