# Generated by Django 5.2.13 on 2026-05-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_seed_platform_landings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('notified', 'Notificada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Si se especifica, sólo se avisa cuando vuelve stock para ESE plan en particular.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_in_stock_alerts', to='catalog.plan', verbose_name='Plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_alerts', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Alerta de stock',
                'verbose_name_plural': 'Alertas de stock',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'status'], name='catalog_bac_product_9490c8_idx'), models.Index(fields=['plan', 'status'], name='catalog_bac_plan_id_77bf42_idx'), models.Index(fields=['email', 'status'], name='catalog_bac_email_9dbbf3_idx')],
            },
        ),
    ]
