# Generated by Django 5.2.13 on 2026-05-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlanding',
            name='slug',
            field=models.SlugField(help_text='Se usa en la URL: ecormecejhelizstore.com/plataforma/<slug>/', max_length=80, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
