# Generated by Django 5.2.14 on 2026-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_promobanner_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_customer_channel_url',
            field=models.URLField(blank=True, help_text='Canal público de avisos para clientes finales (ofertas, novedades).', verbose_name='Canal Telegram – clientes'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_distributor_channel_url',
            field=models.URLField(blank=True, help_text='Canal público con info y avisos para distribuidores.', verbose_name='Canal Telegram – distribuidores'),
        ),
    ]
