# Generated by Django 5.2.14 on 2026-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_promobanner_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlanding',
            name='slug',
            field=models.SlugField(help_text='Se usa en la URL: virtualidadsp.com/plataforma/<slug>/', max_length=80, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
