# Generated by Django 5.2.14 on 2026-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_platformlanding_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_meta_description',
            field=models.CharField(blank=True, default='Cuentas premium oficiales: Netflix, Disney+, Spotify, Office y más. Pago con Binance Pay. Garantía 30 días.', max_length=200, verbose_name='Meta descripción (SEO)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_customer_channel_url',
            field=models.URLField(blank=True, default='', help_text='Canal público de avisos para clientes finales (ofertas, novedades).', verbose_name='Canal Telegram – clientes'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_distributor_channel_url',
            field=models.URLField(blank=True, default='', help_text='Canal público con info y avisos para distribuidores.', verbose_name='Canal Telegram – distribuidores'),
        ),
    ]
