# Generated by Django 5.2.17 on 2026-08-09 02:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="correo")),
                ("encrypted_password", models.TextField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("reserved", "Reservada"),
                            ("sold", "Vendida"),
                            ("review", "En revisión"),
                            ("blocked", "Bloqueada"),
                            ("expired", "Vencida"),
                            ("retired", "Retirada"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True, verbose_name="fecha de compra")),
                ("renewal_date", models.DateField(blank=True, db_index=True, null=True, verbose_name="fecha de renovación")),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="costo de adquisición",
                    ),
                ),
                (
                    "billing_method",
                    models.CharField(
                        choices=[
                            ("card", "Tarjeta"),
                            ("gift_card", "Gift card o saldo"),
                            ("paypal", "PayPal"),
                            ("operator", "Operador"),
                            ("other", "Otro"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="método de pago",
                    ),
                ),
                (
                    "billing_reference",
                    models.CharField(
                        blank=True,
                        help_text="Etiqueta segura o últimos 4 dígitos. Nunca guardes el número completo ni CVV.",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w .-]*$",
                                "Usa solo una etiqueta o últimos 4 dígitos.",
                            )
                        ],
                        verbose_name="referencia de pago",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=80, verbose_name="país o región")),
                ("notes", models.TextField(blank=True, max_length=1000, verbose_name="notas internas")),
                ("last_verified_at", models.DateTimeField(blank=True, null=True, verbose_name="última verificación")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="services.digitalservice",
                        verbose_name="servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta digital",
                "verbose_name_plural": "cuentas digitales",
                "ordering": ("service__name", "email"),
                "indexes": [models.Index(fields=["service", "status"], name="inventory_service_status")],
                "constraints": [models.UniqueConstraint(fields=("service", "email"), name="unique_service_email")],
            },
        ),
    ]
