# Generated by Django 5.2.17 on 2026-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalaccount',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='destacada'),
        ),
    ]
