# Generated by Django 5.2.17 on 2026-08-09 02:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="importe de venta",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("yape", "Yape"),
                            ("plin", "Plin"),
                            ("transfer", "Transferencia"),
                            ("card", "Tarjeta"),
                            ("other", "Otro"),
                        ],
                        max_length=16,
                        verbose_name="método de cobro",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Código de operación o etiqueta segura. Para tarjetas, solo últimos 4 dígitos.",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w .-]*$",
                                "Usa solo letras, números, espacios, punto o guion.",
                            )
                        ],
                        verbose_name="referencia de cobro",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha de venta",
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=500, verbose_name="notas internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="inventory.digitalaccount",
                        verbose_name="cuenta vendida",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "ordering": ("-sold_at", "-pk"),
            },
        ),
    ]
