# Generated by Django 5.2.14 on 2026-05-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=32, unique=True, verbose_name='Chat ID de Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Usuario de Telegram')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=False, help_text='Si está desactivado, el bot no le entrega códigos.', verbose_name='Activo')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Alta')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
            ],
            options={
                'verbose_name': 'Cliente del bot de códigos',
                'verbose_name_plural': 'Clientes del bot de códigos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de la cuenta')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Nota (plataforma/perfil)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='codes.codebotclient', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Correo asignado',
                'verbose_name_plural': 'Correos asignados',
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(fields=('client', 'email'), name='uniq_client_email')],
            },
        ),
    ]
