# Generated by Django 5.2.14 on 2026-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_offset', models.BigIntegerField(default=0, verbose_name='Último update de Telegram')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Estado del bot de códigos',
                'verbose_name_plural': 'Estado del bot de códigos',
            },
        ),
    ]
