# Generated by Django 5.2.16 on 2026-07-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_botstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebotclient',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Cuando pasa esta fecha, el bot deja de entregarle códigos. Vacío = sin vencimiento.', null=True, verbose_name='Vence'),
        ),
        migrations.CreateModel(
            name='CodeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de la cuenta')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='Tipo pedido')),
                ('found', models.BooleanField(default=False, verbose_name='Entregado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='codes.codebotclient', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrega de código',
                'verbose_name_plural': 'Entregas de códigos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client', 'created_at'], name='codes_coded_client__b54dab_idx')],
            },
        ),
    ]
