# Generated by Django 5.2.17 on 2026-08-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_codedelivery_deduplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisneyBotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=32, unique=True, verbose_name='Chat ID de Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Usuario de Telegram')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Alta')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
            ],
            options={
                'verbose_name': 'Cliente del bot Disney+',
                'verbose_name_plural': 'Clientes del bot Disney+',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DisneyAssignedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de la cuenta')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='codes.disneybotclient', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Correo Disney+ asignado',
                'verbose_name_plural': 'Correos Disney+ asignados',
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(fields=('client', 'email'), name='uniq_disney_client_email')],
            },
        ),
        migrations.CreateModel(
            name='DisneyCodeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de la cuenta')),
                ('found', models.BooleanField(default=False, verbose_name='Entregado')),
                ('payload_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Huella del código')),
                ('duplicate', models.BooleanField(default=False, verbose_name='Código repetido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='codes.disneybotclient', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrega de código Disney+',
                'verbose_name_plural': 'Entregas de códigos Disney+',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client', 'created_at'], name='codes_disne_client__468b10_idx')],
            },
        ),
    ]
