# Generated by Django 5.2.13 on 2026-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Preferencias adicionales (idioma, recordatorio de vencimiento, etc).', verbose_name='Notas del cliente'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_pin',
            field=models.CharField(blank=True, help_text='PIN numérico que el cliente quiere en su perfil.', max_length=8, verbose_name='PIN solicitado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_profile_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre del perfil solicitado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('preparing', 'En preparación'), ('delivered', 'Entregado'), ('canceled', 'Cancelado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
