# Generated by Django 5.2.13 on 2026-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_customer_notes_orderitem_requested_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yape_enabled', models.BooleanField(default=False, verbose_name='Yape activo')),
                ('yape_holder_name', models.CharField(blank=True, help_text='Nombre que aparece al transferir por Yape, ej: Jhonatan Molina.', max_length=120, verbose_name='Nombre del titular (Yape)')),
                ('yape_phone', models.CharField(blank=True, help_text='Celular asociado a Yape, ej: +51 999 999 999.', max_length=30, verbose_name='Número Yape')),
                ('yape_qr', models.ImageField(blank=True, help_text='Captura o export del QR de tu cuenta Yape.', upload_to='payments/yape/', verbose_name='QR de Yape')),
                ('yape_instructions', models.TextField(blank=True, help_text='Texto adicional bajo el QR (ej: horario, verificación extra).', verbose_name='Instrucciones extra')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de pagos',
                'verbose_name_plural': 'Configuración de pagos',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Captura del comprobante Yape subida por el cliente.', upload_to='payments/proofs/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, help_text='Visible para el cliente cuando el comprobante es rechazado.', verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de pago'), ('verifying', 'Verificando pago'), ('paid', 'Pagado'), ('preparing', 'En preparación'), ('delivered', 'Entregado'), ('canceled', 'Cancelado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
