# Generated by Django 5.2.13 on 2026-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_plan_low_stock_alert_sent_at_and_more'),
        ('orders', '0003_paymentsettings_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expiry_reminder_1d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expiry_reminder_3d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['expires_at'], name='orderitem_expires_idx'),
        ),
    ]
