# Generated by Django 5.2.13 on 2026-04-27 20:31

import orders.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentsettings_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_credentials',
            field=orders.encryption.EncryptedTextField(blank=True),
        ),
    ]
