# Generated by Django 5.2.13 on 2026-04-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_delivered_credentials'),
        ('orders', '0004_orderitem_expiry_reminder_1d_sent_at_and_more'),
    ]

    operations = [
    ]
