# Generated by Django 5.2.13 on 2026-04-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_status_created_idx_and_more'),
        ('orders', '0005_merge_20260427_1607'),
    ]

    operations = [
    ]
