# Generated by Django 5.2.13 on 2026-04-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20260427_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido mayorista',
                'verbose_name_plural': 'Pedidos mayoristas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
