# Generated by Django 5.2.13 on 2026-04-27 23:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_distributororder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código que el cliente escribe en el carrito (ej. NAVIDAD15). Mayúsculas.', max_length=40, unique=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, help_text="Solo visible para el admin, ej: 'Campaña Black Friday 2026'.", max_length=160, verbose_name='Descripción interna')),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje (%)'), ('fixed', 'Monto fijo (S/)')], default='percent', max_length=10, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Si es porcentaje, número de 1 a 100. Si es monto fijo, soles.', max_digits=10, verbose_name='Valor del descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Vacío = sin límite. Cuando se alcanza, el cupón deja de aplicar.', null=True, verbose_name='Máximo de usos totales')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Cuántas veces puede usarlo un mismo cliente. 0 = sin límite.', verbose_name='Máximo por cliente')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usos actuales')),
                ('min_order_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sin mínimo. Si el total del carrito es menor, el cupón no aplica.', max_digits=10, verbose_name='Total mínimo del pedido (S/)')),
                ('audience', models.CharField(choices=[('all', 'Todos'), ('customer', 'Solo cliente final'), ('distributor', 'Solo distribuidor')], default='all', max_length=20, verbose_name='Aplica para')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Snapshot del código por si el cupón se borra después.', max_length=40, verbose_name='Código aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
    ]
