# Generated by Django 5.2.13 on 2026-04-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_received', 'Pedido recibido'), ('order_preparing', 'Pedido en preparación'), ('order_delivered', 'Pedido entregado (credenciales)'), ('yape_received', 'Yape — comprobante recibido'), ('yape_rejected', 'Yape — comprobante rechazado'), ('expiry_reminder', 'Recordatorio de vencimiento'), ('review_request', 'Solicitud de reseña'), ('other', 'Otro')], db_index=True, default='other', max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falló')], db_index=True, default='sent', max_length=10, verbose_name='Estado')),
                ('to_email', models.EmailField(db_index=True, max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enviado')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Log de email',
                'verbose_name_plural': 'Logs de emails',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['-sent_at'], name='emaillog_sent_at_idx')],
            },
        ),
    ]
