# Generated by Django 5.2.13 on 2026-04-30 10:50

import orders.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='credentials_replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='previous_delivered_credentials',
            field=orders.encryption.EncryptedTextField(blank=True),
        ),
    ]
