# Generated by Django 5.2.13 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_credentials_replaced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_customer_name',
            field=models.CharField(blank=True, help_text='Nombre del cliente final del distribuidor (su propio cliente).', max_length=120, verbose_name='Cliente final (revendido)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_customer_notes',
            field=models.CharField(blank=True, help_text='Recordatorios internos del distribuidor sobre este cliente.', max_length=200, verbose_name='Notas del cliente final'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_customer_whatsapp',
            field=models.CharField(blank=True, help_text='Número con código de país, ej: +51999999999.', max_length=30, verbose_name='WhatsApp del cliente final'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reported_broken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reportado como caído'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reported_broken_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nota del reporte'),
        ),
    ]
