# Generated by Django 5.2.13 on 2026-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_final_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='distri_reminder_1d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='distri_reminder_3d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='distri_reminder_7d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
