# Generated by Django 5.2.13 on 2026-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_distri_reminder_1d_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry-run')),
                ('customer_count', models.PositiveIntegerField(default=0, verbose_name='Avisos a clientes')),
                ('distri_count', models.PositiveIntegerField(default=0, verbose_name='Avisos a distribuidores')),
                ('by_window', models.JSONField(blank=True, default=dict, help_text="Ej: {'cliente_3d': 2, 'cliente_1d': 1, 'distri_7d': 0, ...}", verbose_name='Detalle por ventana')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Run de recordatorios',
                'verbose_name_plural': 'Historial de recordatorios',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['-started_at'], name='reminderrun_started_idx')],
            },
        ),
    ]
