# Generated by Django 5.2.13 on 2026-05-04 16:41

import secrets

from django.db import migrations, models


def backfill_renewal_tokens(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.filter(renewal_token="").only("id"):
        OrderItem.objects.filter(pk=item.pk).update(
            renewal_token=secrets.token_urlsafe(24)
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_reminderrunlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='renewal_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=48, verbose_name='Token de renovación'),
        ),
        migrations.RunPython(backfill_renewal_tokens, noop_reverse),
    ]
