# Generated by Django 5.2.13 on 2026-05-04 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_renewal_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='combo_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento automático por armar un combo de varios productos.', max_digits=10, verbose_name='Descuento combo'),
        ),
    ]
