# Generated by Django 5.2.13 on 2026-05-16 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_combo_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='binance_enabled',
            field=models.BooleanField(default=False, verbose_name='Binance Pay activo'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='binance_holder_name',
            field=models.CharField(blank=True, help_text='Nombre que aparece en tu cuenta de Binance.', max_length=120, verbose_name='Titular Binance'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='binance_instructions',
            field=models.TextField(blank=True, help_text='Texto adicional bajo el QR (ej: red recomendada, comisiones, soporte USDT, etc.).', verbose_name='Instrucciones extra Binance'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='binance_pay_id',
            field=models.CharField(blank=True, help_text='Tu Pay ID de Binance (lo encuentras en la app Binance → Pay → recibir).', max_length=80, verbose_name='Binance Pay ID'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='binance_qr',
            field=models.ImageField(blank=True, help_text='Captura o export del QR de Binance Pay para que el cliente lo escanee.', upload_to='payments/binance/', verbose_name='QR de Binance Pay'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('3.7800'), help_text='Cuántos PEN equivalen a 1 USD. Se usa solo para mostrar el equivalente en dólares al lado de cada precio. No afecta el cobro real (que sigue siendo en PEN).', max_digits=8, verbose_name='Tipo de cambio (1 USD = X PEN)'),
        ),
    ]
