# Generated by Django 5.2.13 on 2026-05-16 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_paymentsettings_binance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='usd_rate_auto',
            field=models.BooleanField(default=True, help_text='Si está activo, jalamos el precio promedio USDT/PEN del P2P de Binance cada 30 min. Si la API falla, caemos al TC manual de abajo.', verbose_name='Usar TC automático de Binance P2P'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('3.7800'), help_text='Solo se usa si el TC automático está desactivado o si la API de Binance falla. No afecta el cobro real (que sigue siendo en PEN).', max_digits=8, verbose_name='Tipo de cambio manual (1 USD = X PEN)'),
        ),
    ]
