# Generated by Django 5.2.16 on 2026-07-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_backfill_orderitem_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='yape_enabled',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='yape_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='yape_instructions',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='yape_phone',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='yape_qr',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_accounts',
            field=models.TextField(blank=True, help_text='Datos de las cuentas para depósito/transferencia. Una cuenta por bloque, ej: Banco Guayaquil — Ahorros 0022156352.', verbose_name='Cuentas bancarias'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_enabled',
            field=models.BooleanField(default=False, verbose_name='Depósito bancario activo'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_holder_name',
            field=models.CharField(blank=True, help_text='Nombre del titular de las cuentas bancarias.', max_length=120, verbose_name='Titular de las cuentas'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_instructions',
            field=models.TextField(blank=True, help_text='Texto adicional bajo las cuentas (ej: enviar comprobante, horario).', verbose_name='Instrucciones extra depósito'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Captura del comprobante de pago subida por el cliente.', upload_to='payments/proofs/', verbose_name='Comprobante de pago'),
        ),
    ]
