resolver 127.0.0.11 valid=10s ipv6=off;

upstream api_backend {
  zone api_backend 64k;
  server api:4000 resolve;
}

upstream panel_backend {
  zone panel_backend 64k;
  server panel:3000 resolve;
}

server {
  listen 80;
  server_name marketingjhelizxyz.online www.marketingjhelizxyz.online;
  client_max_body_size 8m;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
  location /api/ { proxy_pass http://api_backend/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
  location / { proxy_pass http://panel_backend; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}
